name: Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: 'apps/mobile'
      
      - name: Expo GitHub Action
        uses: expo/expo-github-action@9.0.0
        with:
          eas-version: latest
          packager: npm
          token: ${{ secrets.EXPO_TOKEN }}
      
      - name: Install dependencies
        run: npm install

      - name: Create update
        run: eas update --auto --non-interactive

